/* SPDX-License-Identifier: MIT */
#include "sink-fault-policy.h"

StpwSinkFaultDisposition
stpw_sink_fault_policy_classify(StpwSinkFaultCause cause) {
  switch (cause) {
  case STPW_SINK_FAULT_CAUSE_RECEIVER_PROOF_UNAVAILABLE:
  case STPW_SINK_FAULT_CAUSE_RECEIVER_PROOF_STALE:
  case STPW_SINK_FAULT_CAUSE_RECEIVER_SOURCE_CONFLICT:
  case STPW_SINK_FAULT_CAUSE_ACTIVATION_LINEAGE_CHANGED:
  case STPW_SINK_FAULT_CAUSE_RECEIVER_TOPOLOGY_CHANGED:
  case STPW_SINK_FAULT_CAUSE_LOCAL_CONTROL_COLLISION:
  case STPW_SINK_FAULT_CAUSE_LOCAL_CONTROL_BACKPRESSURE:
  case STPW_SINK_FAULT_CAUSE_CONTROL_CHANNEL_LOST_IDLE:
    return STPW_SINK_FAULT_KEEP_BLOCKED;

  case STPW_SINK_FAULT_CAUSE_WRITE_OUTCOME_UNKNOWN:
  case STPW_SINK_FAULT_CAUSE_RECEIVER_UNSAFE_TRANSITION:
    return STPW_SINK_FAULT_WRITE_UNCERTAIN;

  case STPW_SINK_FAULT_CAUSE_PIPEWIRE_NODE_FAILED:
  case STPW_SINK_FAULT_CAUSE_SAFETY_GATE_UNAVAILABLE:
    return STPW_SINK_FAULT_RECREATE_NODE;

  case STPW_SINK_FAULT_CAUSE_ENDPOINT_UNAVAILABLE:
  case STPW_SINK_FAULT_CAUSE_RAOP_UNAVAILABLE:
  case STPW_SINK_FAULT_CAUSE_IDENTITY_MISMATCH:
  case STPW_SINK_FAULT_CAUSE_SERVICE_STOP:
  case STPW_SINK_FAULT_CAUSE_PROMOTED_FOLLOWER_RETIREMENT:
  case STPW_SINK_FAULT_CAUSE_PROMOTED_MASTER_RETIREMENT:
    return STPW_SINK_FAULT_WITHDRAW_UNAVAILABLE;

  case STPW_SINK_FAULT_CAUSE_N_VALUES:
    break;
  }

  return STPW_SINK_FAULT_RECREATE_NODE;
}
